### ISSUE TITLE
Please add arm architecture

### ISSUE THREAD

**Issue by Iamafnan** [actboy168/bee.lua#22]
I was trying to build luamake and when I started building it then some error pops up and shows that my device architecture is not supported
Please add support for arm

**Comment by actboy168** [comment]
What is the error message? What is your operating system and architecture?

**Comment by Iamafnan** [comment]
My os is android and my architecture is arm

**Comment by actboy168** [comment]
Please provide detailed information.

**Comment by actboy168** [comment]
I don't have a test environment, but maybe this fix 9132c7ecb4a68c40d52a6d750308237bf054feb6 can solve your problem.

**Comment by Iamafnan** [comment]
Thanks the error got fixed but there is some issue which luamake this error pops up at the ending of the compilation 
![IMG_20211210_204049](https://user-images.githubusercontent.com/80388154/145596234-4cc09ee6-47ef-43e0-979e-d14148d34090.jpg)

**Comment by actboy168** [comment]
I think you should ask your terminal provider.

**Comment by Iamafnan** [comment]
Okey thanks for the help 👍
