### ISSUE TITLE
Fails to build on Fedora 38/Rawhide

### ISSUE THREAD

**Issue by YorickPeterse** [actboy168/bee.lua#32]
I'm trying to build https://github.com/LuaLS/lua-language-server for Fedora. For Fedora 37 it works fine, but on Fedora 38/Rawhide I run into the following errors:

```
FAILED: build/linux/obj/source_bee/lua_serialization.obj 
gcc -MMD -MT build/linux/obj/source_bee/lua_serialization.obj -MF build/linux/obj/source_bee/lua_serialization.obj.d -std=c++17 -fno-rtti -O2 -Wall -Werror -fvisibility=hidden -I3rd/bee.lua/3rd/lua-seri -I3rd/bee.lua -Itools/lua54 -DBEE_STATIC -DNDEBUG -fPIC -o build/linux/obj/source_bee/lua_serialization.obj -c 3rd/bee.lua/binding/lua_serialization.cpp
3rd/bee.lua/binding/lua_serialization.cpp: In function 'int bee::lua_serialization::lightuserdata(lua_State*)':
3rd/bee.lua/binding/lua_serialization.cpp:34:33: error: 'intptr_t' was not declared in this scope
   34 |             lua_pushinteger(L, (intptr_t)lua_touserdata(L, 1));
      |                                 ^~~~~~~~
3rd/bee.lua/binding/lua_serialization.cpp:5:1: note: 'intptr_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
    4 | #include <lua-seri.h>
  +++ |+#include <cstdint>
    5 | }
[17/31] Compile C++ build/linux/obj/source_bee/lua_socket.obj
[18/31] Compile C++ build/linux/obj/source_bee/lua_filesystem.obj
ninja: build stopped: subcommand failed.
error: Bad exit status from /var/tmp/rpm-tmp.01qIgC (%build)
```

Looking at the source code, the only place this header is included at is [here](https://github.com/actboy168/bee.lua/blob/93a007c59db5a917744a4f5980d369f6fdea7b62/bee/nonstd/3rd/fmt/format.h#L37). The header [binding.h](https://github.com/actboy168/bee.lua/blob/master/binding/binding.h) doesn't seem to include `cstdint` either.

I'm guessing this is because Fedora 38 includes a newer version of GCC (https://fedoraproject.org/wiki/Changes/GNUToolchainF38#Summary), and perhaps that version no longer includes this header for you?

**Comment by actboy168** [comment]
Thanks.

**Comment by YorickPeterse** [comment]
@actboy168 Thanks, this fixes the problem for `master`. Unfortunately, the commit used by Lua language server (9f270f3b7f394d32a57c70fb6d45e2b4317ce4e3) continues to fail with the equivalent changes made. I'll see what needs to be done to get that working :smiley:
