### ISSUE TITLE
Lua bug

### ISSUE THREAD

**Issue by cloudwu** [actboy168/bee.lua#51]
我刚才遇到 Lua 的一个 bug ，核对后和这个月邮件列表中提到的是同一个。

麻烦 patch 一下，合并到 ant 。不然我现在写的游戏代码跑不了了 :D

https://lua.org/bugs.html

这里 5.4.7 下第二个 bug 需要改 lcode.c 中 `luaK_exp2val` 函数。

**Comment by actboy168** [comment]
这个patch居然没有推送到git

**Comment by actboy168** [comment]
Done.

**Comment by cloudwu** [comment]
可能是希望有个更彻底的改法。这个 if 的临时感太强
