### ISSUE TITLE
lua版本

### ISSUE THREAD

**Issue by w0x12e** [actboy168/bee.lua#7]
YD里面用的是lua5.3 这里面用的是lua5.4
到底用哪个版本

**Comment by actboy168** [comment]
我不明白你的问题是什么

**Comment by oxpy** [comment]
YD里面用的lua是5.3版本吧？
YD用的beelua里面用的是5.4版本吧？

**Comment by actboy168** [comment]
你可以用`print(_VERSION)`来确定版本

**Comment by oxpy** [comment]
大神，是这样，我想确认一下，YDWE里面依赖lua5.3 还是5.4呢，因为YD里面看到lua53.dll,beelua里面看到源码是lua5.4的，

**Comment by actboy168** [comment]
不同版本的YDWE对应不同版本的lua

**Comment by oxpy** [comment]
1.32版本的用什么版本的beelua呢

**Comment by luciouskami** [comment]
从1.32开始YDWE使用的都是最新的lua 5.4版本
